base: &base
  adapter: postgresql
  encoding: utf8
  username:
  password:
  host: 127.0.0.1
  pool: 5

production:
  <<: *base
  database: dj_mon_demo_production

development:
  <<: *base
  database: dj_mon_demo_development

test: &test
  <<: *base
  database: dj_mon_demo_test
